services:
    # Our Python app "RadAPI":
    # it will run on http://localhost:8000
    radapi:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        depends_on:
            mydb:
                condition: service_healthy
        # I just wanna run two commands and have to use this ugly syntax, really Docker?
        # First, we insert some initial data then we run the Uvicorn web server.
        command: >
            sh -c "python initial_data.py
            && uvicorn api:app --host 0.0.0.0 --port 8000"
        ports:
            - "8000:8000"
    # MySQL database with FreeRADIUS schema
    mydb:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: mypass
        volumes:
            - ./freeradius-mysql/1-database.sql:/docker-entrypoint-initdb.d/1.sql
            - ./freeradius-mysql/2-schema.sql:/docker-entrypoint-initdb.d/2.sql
            - ./freeradius-mysql/3-setup.sql:/docker-entrypoint-initdb.d/3.sql
            - myvol:/var/lib/mysql
        healthcheck:
            test: mysqladmin ping
            interval: 20s
            timeout: 5s
            retries: 3
    # phpMyAdmin web interface (optional):
    # it will run on http://localhost:8080 (root/mypass or raduser/radpass)
    myadmin:
        image: phpmyadmin
        depends_on:
            mydb:
                condition: service_healthy
        environment:
            - PMA_HOST=mydb
        ports:
            - "8080:80"
volumes:
    myvol:
