services:
  # Our Python app "RadAPI":
  # it will run on http://localhost:8000
  radapi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    depends_on:
      - mydb
    # In production, we don't populate development data
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      # Database configuration
      - DB_DRIVER=mysql.connector
      - DB_NAME=raddb
      - DB_USER=raduser
      - DB_PASS=radpass
      - DB_HOST=mydb
      - DB_PORT=3306
      # API configuration
      - API_URL=http://localhost:8000
      - API_HOST=0.0.0.0
      - API_PORT=8000
      # Pagination settings
      - ITEMS_PER_PAGE=100
      # Table names
      - TABLE_RADCHECK=radcheck
      - TABLE_RADREPLY=radreply
      - TABLE_RADGROUPCHECK=radgroupcheck
      - TABLE_RADGROUPREPLY=radgroupreply
      - TABLE_RADUSERGROUP=radusergroup
      - TABLE_NAS=nas
      # Application settings
      - ENV=prod
      - DEBUG=false
      - LOG_LEVEL=INFO
  # MySQL database with FreeRADIUS schema
  mydb:
    image: mariadb:11.7.2-noble
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - ./freeradius-mysql/1-database.sql:/docker-entrypoint-initdb.d/1.sql
      - ./freeradius-mysql/2-schema.sql:/docker-entrypoint-initdb.d/2.sql
      - ./freeradius-mysql/3-setup.sql:/docker-entrypoint-initdb.d/3.sql
      - freeradius-mariadb:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD:-root}",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
  # phpMyAdmin web interface (optional):
  # it will run on http://localhost:8080 (root/mypass or raduser/radpass)
  myadmin:
    image: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mydb
    environment:
      - PMA_HOST=mydb
      - PMA_USER=${DB_USER:-raduser}
      - PMA_PASSWORD=${DB_PASS:-radpass}
    ports:
      - "${PMA_PORT:-8080}:80"
volumes:
  freeradius-mariadb: