name: Python package

on:
  push:
    branches: ["master"]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Start MySQL service
      run: |
        sudo systemctl start mysql.service
    - name: Init database
      run: |
        mysql -uroot -proot < docker/freeradius-mysql/1-database.sql
        mysql -uroot -proot < docker/freeradius-mysql/2-schema.sql
        mysql -uroot -proot < docker/freeradius-mysql/3-setup.sql
    - name: Add mydb alias for localhost (used by database.py)
      run: |
        echo "127.0.0.1 mydb" | sudo tee -a /etc/hosts
        ping -c 3 mydb
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-dev.txt
    - name: Check code formatting
      run: |
        black --check .
    - name: Check static typing
      run: |
        mypy .
    - name: Run tests
      run: |
        pytest -v --cov-report term --cov=. src/tests/
